import "@/styles/globals.css";

import type { Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
  <html className={GeistSans.variable} lang="en">
    <body>
      <TRPCReactProvider>{children}</TRPCReactProvider>
    </body>
  </html>
);

export default RootLayout;
